export type Challenge = {
  id: number
  word: string
  tip: string
}

export const WORDS: Challenge[] = [
  { id: 1, word: "CSS", tip: "Linguagem de estilos" },
  { id: 2, word: "REACT", tip: "Biblioteca para criar interfaces Web" },
  { id: 3, word: "HTML", tip: "Linguagem de marcação" },
  {
    id: 4,
    word: "Javascript",
    tip: "Uma das linguagens de programação mais utilizadas no mundo",
  },
  { id: 5, word: "Typescript", tip: "Para adicionar tipagem no Javascript" },
  { id: 6, word: "Elefante", tip: "Maior mamífero terrestre da atualidade" },
  { id: 7, word: "Girafa", tip: "Animal com o pescoço mais longo do mundo" },
  { id: 8, word: "Tigre", tip: "Felino selvagem conhecido pelas listras alaranjadas e pretas" },
  { id: 9, word: "Pinguim", tip: "Ave que não voa e vive em regiões geladas" },
  { id: 10, word: "Borboleta", tip: "Inseto colorido que nasce de uma lagarta" },
  { id: 11, word: "Cachorro", tip: "Animal doméstico conhecido como o melhor amigo do homem" },
  { id: 12, word: "Brasil", tip: "País-sede da Copa do Mundo de 2014" },
  { id: 13, word: "Egito", tip: "País africano famoso pelas pirâmides" },
  { id: 14, word: "Oceano", tip: "Grande extensão de água salgada que cobre a maior parte do planeta" },
  { id: 15, word: "Montanha", tip: "Elevação natural do terreno, geralmente rochosa" },
  { id: 16, word: "Futebol", tip: "Esporte mais popular do Brasil" },
  { id: 17, word: "Basquete", tip: "Esporte jogado com uma bola laranja e uma cesta" },
  { id: 18, word: "Ciclismo", tip: "Esporte praticado com uma bicicleta" },
  { id: 19, word: "Piano", tip: "Instrumento musical de teclas, cordas e martelos" },
  { id: 20, word: "Bateria", tip: "Instrumento musical de percussão, comum em bandas de rock" },
  { id: 21, word: "Guitarra", tip: "Instrumento de cordas elétrico muito usado no rock" },
  { id: 22, word: "Chocolate", tip: "Doce feito a partir do cacau" },
  { id: 23, word: "Abacaxi", tip: "Fruta tropical com casca espinhosa e coroa de folhas" },
  { id: 24, word: "Banana", tip: "Fruta amarela, rica em potássio" },
  { id: 25, word: "Hamburguer", tip: "Sanduíche popular em lanchonetes de fast food" },
  { id: 26, word: "Sorvete", tip: "Sobremesa gelada e doce, perfeita para dias quentes" },
  { id: 27, word: "Carnaval", tip: "Festa popular brasileira cheia de música e fantasias" },
  { id: 28, word: "Astronauta", tip: "Profissional que viaja para o espaço" },
  { id: 29, word: "Planeta", tip: "Corpo celeste que orbita uma estrela" },
  { id: 30, word: "Foguete", tip: "Veículo usado para viagens espaciais" },
  { id: 31, word: "Dinossauro", tip: "Réptil gigante que viveu há milhões de anos" },
  { id: 32, word: "Terremoto", tip: "Tremor causado pelo movimento das placas tectônicas" },

  // Animais
  { id: 33, word: "Leao", tip: "Conhecido como o rei da selva" },
  { id: 34, word: "Macaco", tip: "Primata conhecido por sua agilidade em subir em árvores" },
  { id: 35, word: "Zebra", tip: "Animal africano com listras pretas e brancas" },
  { id: 36, word: "Coelho", tip: "Mamífero de orelhas compridas, símbolo da Páscoa" },
  { id: 37, word: "Tartaruga", tip: "Réptil de casco rígido, famoso por sua lentidão" },
  { id: 38, word: "Golfinho", tip: "Mamífero marinho muito inteligente e sociável" },
  { id: 39, word: "Tubarao", tip: "Peixe predador temido pelos oceanos" },
  { id: 40, word: "Cavalo", tip: "Animal usado para montaria e tração desde a antiguidade" },
  { id: 41, word: "Vaca", tip: "Animal que produz o leite consumido no mundo todo" },
  { id: 42, word: "Porco", tip: "Animal de fazenda associado à produção de bacon e presunto" },
  { id: 43, word: "Galinha", tip: "Ave de criação que põe ovos" },
  { id: 44, word: "Aguia", tip: "Ave de rapina símbolo de força e liberdade" },
  { id: 45, word: "Coruja", tip: "Ave noturna conhecida pela visão aguçada no escuro" },
  { id: 46, word: "Lobo", tip: "Animal selvagem que vive e caça em matilha" },
  { id: 47, word: "Urso", tip: "Mamífero grande e peludo, símbolo do Ártico" },
  { id: 48, word: "Panda", tip: "Urso preto e branco que se alimenta principalmente de bambu" },
  { id: 49, word: "Canguru", tip: "Marsupial australiano que se desloca aos saltos" },
  { id: 50, word: "Rinoceronte", tip: "Grande mamífero com chifre no focinho" },
  { id: 51, word: "Crocodilo", tip: "Réptil predador que vive em rios e pântanos" },
  { id: 52, word: "Morcego", tip: "Único mamífero capaz de voar de verdade" },
  { id: 53, word: "Esquilo", tip: "Pequeno roedor conhecido por armazenar nozes" },
  { id: 54, word: "Raposa", tip: "Animal astuto, símbolo de esperteza no folclore" },
  { id: 55, word: "Foca", tip: "Mamífero marinho que vive em regiões frias" },
  { id: 56, word: "Baleia", tip: "Maior animal do planeta, vive nos oceanos" },
  { id: 57, word: "Polvo", tip: "Molusco com oito tentáculos e grande inteligência" },
  { id: 58, word: "Caranguejo", tip: "Crustáceo que anda de lado" },
  { id: 59, word: "Camarao", tip: "Crustáceo pequeno muito usado na culinária" },
  { id: 60, word: "Aranha", tip: "Aracnídeo de oito patas que tece teias" },
  { id: 61, word: "Formiga", tip: "Inseto social conhecido pelo trabalho em equipe" },
  { id: 62, word: "Abelha", tip: "Inseto que produz mel e poliniza flores" },

  // Frutas
  { id: 63, word: "Morango", tip: "Fruta vermelha pequena, muito usada em sobremesas" },
  { id: 64, word: "Uva", tip: "Fruta usada na produção de vinho e suco" },
  { id: 65, word: "Melancia", tip: "Fruta grande e suculenta, perfeita para o verão" },
  { id: 66, word: "Manga", tip: "Fruta tropical doce e suculenta" },
  { id: 67, word: "Laranja", tip: "Fruta cítrica rica em vitamina C" },
  { id: 68, word: "Limao", tip: "Fruta cítrica azeda, usada em sucos e temperos" },
  { id: 69, word: "Maca", tip: "Fruta que, segundo a lenda, teria caído na cabeça de Newton" },
  { id: 70, word: "Pera", tip: "Fruta doce de formato característico" },
  { id: 71, word: "Mamao", tip: "Fruta alaranjada por dentro, boa para a digestão" },
  { id: 72, word: "Melao", tip: "Fruta doce de casca rígida e polpa macia" },
  { id: 73, word: "Kiwi", tip: "Fruta de casca peluda e polpa verde" },
  { id: 74, word: "Coco", tip: "Fruta tropical com água refrescante dentro" },
  { id: 75, word: "Cereja", tip: "Fruta pequena e vermelha, símbolo de sobremesas finas" },
  { id: 76, word: "Goiaba", tip: "Fruta usada para fazer goiabada" },

  // Comidas
  { id: 77, word: "Lasanha", tip: "Prato italiano em camadas de massa, molho e queijo" },
  { id: 78, word: "Macarrao", tip: "Massa muito usada na culinária italiana" },
  { id: 79, word: "Feijao", tip: "Ingrediente básico da culinária brasileira, acompanha o arroz" },
  { id: 80, word: "Arroz", tip: "Cereal que é a base da alimentação em várias culturas" },
  { id: 81, word: "Sanduiche", tip: "Comida feita com pão recheado" },
  { id: 82, word: "Pipoca", tip: "Petisco feito de milho estourado" },
  { id: 83, word: "Bolo", tip: "Doce assado tradicional em festas de aniversário" },
  { id: 84, word: "Torta", tip: "Prato doce ou salgado feito com massa e recheio" },
  { id: 85, word: "Sopa", tip: "Prato líquido e quente, ideal para dias frios" },
  { id: 86, word: "Churrasco", tip: "Carne grelhada, tradição muito popular no Brasil" },
  { id: 87, word: "Coxinha", tip: "Salgado brasileiro em formato de gota, recheado com frango" },
  { id: 88, word: "Pastel", tip: "Salgado frito, muito vendido em feiras" },
  { id: 89, word: "Brigadeiro", tip: "Doce brasileiro feito de chocolate e leite condensado" },
  { id: 90, word: "Pudim", tip: "Sobremesa cremosa com calda de caramelo" },
  { id: 91, word: "Queijo", tip: "Derivado do leite, usado em diversos pratos" },
  { id: 92, word: "Batata", tip: "Tubérculo usado em frituras e purês" },

  // Esportes
  { id: 93, word: "Volei", tip: "Esporte jogado com as mãos por cima de uma rede" },
  { id: 94, word: "Natacao", tip: "Esporte praticado dentro da água" },
  { id: 95, word: "Tenis", tip: "Esporte praticado com raquete e uma bolinha amarela" },
  { id: 96, word: "Corrida", tip: "Modalidade de atletismo que testa a velocidade" },
  { id: 97, word: "Boxe", tip: "Esporte de combate praticado com socos e luvas" },
  { id: 98, word: "Judo", tip: "Arte marcial japonesa baseada em quedas e imobilizações" },
  { id: 99, word: "Karate", tip: "Arte marcial japonesa que usa golpes de mão e pé" },
  { id: 100, word: "Surfe", tip: "Esporte praticado em cima de uma prancha nas ondas do mar" },
  { id: 101, word: "Skate", tip: "Esporte praticado sobre uma prancha com rodinhas" },
  { id: 102, word: "Xadrez", tip: "Jogo de tabuleiro estratégico com peças como rei e rainha" },

  // Profissões
  { id: 103, word: "Medico", tip: "Profissional responsável por cuidar da saúde das pessoas" },
  { id: 104, word: "Professor", tip: "Profissional responsável por ensinar em sala de aula" },
  { id: 105, word: "Engenheiro", tip: "Profissional que projeta estruturas e sistemas" },
  { id: 106, word: "Advogado", tip: "Profissional que representa pessoas na Justiça" },
  { id: 107, word: "Dentista", tip: "Profissional que cuida da saúde bucal" },
  { id: 108, word: "Bombeiro", tip: "Profissional que combate incêndios e faz resgates" },
  { id: 109, word: "Policial", tip: "Profissional responsável pela segurança pública" },
  { id: 110, word: "Piloto", tip: "Profissional responsável por conduzir aviões" },
  { id: 111, word: "Jornalista", tip: "Profissional que investiga e divulga notícias" },
  { id: 112, word: "Musico", tip: "Profissional que compõe ou interpreta música" },
  { id: 113, word: "Pintor", tip: "Profissional ou artista que cria obras com tinta" },
  { id: 114, word: "Ator", tip: "Profissional que interpreta personagens no cinema ou teatro" },
  { id: 115, word: "Cantor", tip: "Profissional que interpreta músicas com a voz" },
  { id: 116, word: "Veterinario", tip: "Profissional que cuida da saúde dos animais" },

  // Objetos do dia a dia
  { id: 117, word: "Celular", tip: "Aparelho usado para fazer ligações e acessar a internet" },
  { id: 118, word: "Computador", tip: "Equipamento eletrônico usado para processar dados" },
  { id: 119, word: "Televisao", tip: "Aparelho usado para assistir programas e filmes" },
  { id: 120, word: "Geladeira", tip: "Eletrodoméstico usado para conservar alimentos gelados" },
  { id: 121, word: "Bicicleta", tip: "Veículo de duas rodas movido a pedal" },
  { id: 122, word: "Relogio", tip: "Objeto usado para marcar as horas" },
  { id: 123, word: "Oculos", tip: "Acessório usado para corrigir ou proteger a visão" },
  { id: 124, word: "Mochila", tip: "Bolsa usada nas costas para carregar objetos" },
  { id: 125, word: "Espelho", tip: "Objeto que reflete a imagem de quem está na frente" },
  { id: 126, word: "Sombrinha", tip: "Usada para proteção contra a chuva ou o sol" },

  // Natureza e espaço
  { id: 127, word: "Floresta", tip: "Área com grande concentração de árvores e vida selvagem" },
  { id: 128, word: "Deserto", tip: "Região árida com pouquíssima chuva" },
  { id: 129, word: "Cachoeira", tip: "Queda d'água natural, comum em trilhas" },
  { id: 130, word: "Ilha", tip: "Porção de terra cercada de água por todos os lados" },
  { id: 131, word: "Praia", tip: "Faixa de areia à beira do mar" },
  { id: 132, word: "Caverna", tip: "Cavidade natural formada em rochas ou montanhas" },
  { id: 133, word: "Vulcao", tip: "Montanha que pode expelir lava e gases do interior da Terra" },
  { id: 134, word: "Estrela", tip: "Corpo celeste que brilha com luz própria" },
  { id: 135, word: "Cometa", tip: "Corpo celeste com uma cauda brilhante, visível periodicamente" },
  { id: 136, word: "Galaxia", tip: "Enorme conjunto de estrelas, planetas e poeira cósmica" },
  { id: 137, word: "Universo", tip: "Tudo o que existe: espaço, tempo, matéria e energia" },
  { id: 138, word: "Furacao", tip: "Tempestade giratória muito forte, comum em regiões tropicais" },
  { id: 139, word: "Tornado", tip: "Coluna de vento giratória extremamente destrutiva" },
  { id: 140, word: "Arcoiris", tip: "Fenômeno óptico colorido que aparece após a chuva" },

  // Países
  { id: 141, word: "Portugal", tip: "País europeu que colonizou o Brasil" },
  { id: 142, word: "Espanha", tip: "País europeu famoso pelo flamenco e a paella" },
  { id: 143, word: "Franca", tip: "País europeu conhecido pela Torre Eiffel" },
  { id: 144, word: "Alemanha", tip: "País europeu conhecido pela Oktoberfest e a indústria automotiva" },
  { id: 145, word: "Italia", tip: "País europeu com formato de bota, famoso pela pizza e massas" },
  { id: 146, word: "Japao", tip: "País asiático conhecido como a terra do sol nascente" },
  { id: 147, word: "China", tip: "País mais populoso do mundo, na Ásia" },
  { id: 148, word: "India", tip: "País asiático conhecido pelo Taj Mahal" },
  { id: 149, word: "Canada", tip: "País norte-americano conhecido pelas folhas de bordo" },
  { id: 150, word: "Argentina", tip: "País sul-americano vizinho do Brasil, famoso pelo tango" },
  { id: 151, word: "Mexico", tip: "País norte-americano conhecido pelos tacos e pelas pirâmides maias" },
  { id: 152, word: "Russia", tip: "Maior país do mundo em extensão territorial" },
  { id: 153, word: "Australia", tip: "País-continente famoso por cangurus e coalas" },
  { id: 154, word: "Grecia", tip: "País berço da civilização ocidental e dos Jogos Olímpicos" },

  // Música e transportes
  { id: 155, word: "Violino", tip: "Instrumento de cordas tocado com um arco" },
  { id: 156, word: "Flauta", tip: "Instrumento musical de sopro" },
  { id: 157, word: "Saxofone", tip: "Instrumento de sopro muito usado no jazz" },
  { id: 158, word: "Trompete", tip: "Instrumento de sopro metálico usado em bandas e orquestras" },
  { id: 159, word: "Violao", tip: "Instrumento de cordas acústico muito popular no Brasil" },
  { id: 160, word: "Aviao", tip: "Veículo usado para viagens aéreas" },
  { id: 161, word: "Trem", tip: "Veículo que se desloca sobre trilhos" },
  { id: 162, word: "Navio", tip: "Grande embarcação usada para transporte marítimo" },
  { id: 163, word: "Onibus", tip: "Veículo usado para transporte coletivo urbano" },
  { id: 164, word: "Submarino", tip: "Embarcação capaz de navegar debaixo d'água" },
]
